packages:
  - 'sdk'
  - 'docs'
  - 'experiments/billable'
  - 'experiments/applywize'
  - 'experiments/yt-dos'
  - 'experiments/cutable'
  - 'starters/minimal'
  - 'starters/prisma'
  - 'starters/drizzle'
