#:schema node_modules/wrangler/config-schema.json
name = "__change_me__"
main = "src/worker.tsx"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { binding = "ASSETS", directory = "public" }

[[ d1_databases ]]
binding = "DB"
database_name = "__change_me__"
database_id = "__change_me__"
migrations_dir = "drizzle"

[observability]
enabled = true

[vars]
